### ISSUE TITLE
Proposal: change/update AI skill values

### ISSUE THREAD

**Issue by shadow-fa** [folkarps/F3#178] opened 2018-06-10 17:38 UTC
[See below]

**edit: moved refactor discussion to #183. moved 
Note that the following discussion might refer to the already refactored ai skill matrix from #183**

**Comment by ninjaProtocol** [comment] 2018-06-23 20:05
The problem isn't the documentation (although between F3 and the BI wiki, i did end up confused), but it's the clarity of what the final skill values are. It's weird to put in out-of-range values and then put it through another multiplier, and have a mission maker calculate the whole matrix. As it is, the skill values go through a number of interpolations that make it difficult to predict what the final outcome is, either on paper or in practice. To quote from the [wiki](https://community.bistudio.com/wiki/AI_Sub-skills#Notes):

> Each sub-skill is used in several calculations. Value of each sub-skill is inherited from the value set by skill slider in Insert Unit dialogue or setSkill command, or more precisely with setSkill alternative syntax. This value is interpolated into ranges defined in CfgAISkill and multiplied by a value of AI Level Skill or Precision set in player's profile (.Arma3Profile file).

... or in our case, the server profile.
```
class CustomAILevel
{
	skillAI=0.80000013;
	precisionAI=0.20000009;
};
```

1Tac [for example](https://github.com/Sniperhid/1tac_misc/blame/master/addons/tm_ai_tweaks/config.cpp) use skillAI of 1 and precisionAI of 0.3. 

Going by [this post](https://forums.bohemia.net/forums/topic/150499-ai-discussion-dev-branch/?page=201&tab=comments#comment-3290389) that introduces a maximum increase of 0.34 to the subskill values.

Further, aimingSpeed is remapped to a [0.5, 1] range in CfgAISkill.

Anyway, the refactored array you've suggested is way more clear, reading that I know exactly what the current sub-skill values are and make changes accordingly if needed. Probably might be a good idea to run these values with the appropriate precisionAI and SkillAI values and produce a table of `skillFinal` results, and stick it in our wiki. 

Given the changes to the curves that took place in [August](https://forums.bohemia.net/forums/topic/150499-ai-discussion-dev-branch/?do=findComment&comment=3220586), it's probably good to revise these values anyway. I'm not sure if a difference between 0.42 and 0.49 is even going to be noticeable. These values haven't been tweaked since 2015 anyway, and a fair few things have changed since.

I'd suggest the following (keeping in mind this is based on intuition + reading around):
```
f_var_skillSet = [
	//Super	High	Medium	Low
	[ 0.5,	0.4,	0.3,	0.2,	],  // aimingAccuracy
	[ 0.5,	0.4,	0.3,	0.2,	],  // aimingShake
	[ 0.6,	0.4,	0.2,	0,	],  // aimingSpeed
	[ 1,	0.75,	0.5,	0.3,	],  // spotDistance
	[ 0.7,	0.5,	0.4,	0.3,	],  // spotTime
	[ 1,	0.9,	0.7,	0.6,	],  // courage
	[ 1,	1,	0.8,	0.75,	],  // reloadSpeed*
	[ 1,	1,	1,	1,	],  // commanding
	[ 1,	1,	0.8,	0.6,	],  // general
];
```
*according to 1Tac github + Bear of 1Tac:
>reloadSpeed apparently breaks rapid firing in single fire mode for players
>iirc if you fired semi very fast it would stop firing

Perhaps why it was set to 1 everywhere, in which case we shouldn't change it.

Anyway, I dare say having 4 levels is useless - just drop Low and rename Super, High, Medium to High, Medium and Low (or something). At present we rarely use Super and probably never use Low.

I had originally thought of making it terrain dependent, for example:
```
f_var_skillSet = [
	//Open	All	Urban	Jungle
	[ 0.5,	0.4,	0.3,	0.2,	],  // aimingAccuracy
	[ 0.5,	0.4,	0.3,	0.2,	],  // aimingShake
	[ 0.5,	0.4,	0.2,	0,	],  // aimingSpeed
	[ 1,	0.7,	0.4,	0.1,	],  // spotDistance
	[ 0.7,	0.5,	0.4,	0.2,	],  // spotTime
	[ 1,	0.9,	0.6,	0.5,	],  // courage
	[ 1,	1,	0.8,	0.75,	],  // reloadSpeed*
	[ 1,	1,	1,	1,	],  // commanding
	[ 1,	1,	0.6,	0.4,	],  // general
];
```
I find this more useful (as both a mission maker and a host) to select what difficulty to set it at by default.

**Comment by shadow-fa** [comment] 2018-06-24 13:00
> Anyway, I dare say having 4 levels is useless - just drop Low and rename Super, High, Medium to High, Medium and Low (or something). At present we rarely use Super and probably never use Low.

I disagree. We have quite a few missions that use "Low" by default. If anything "Super" is the one we never use. (I might scan all our missions and check how many missions exactly use which setting.) 
However I don't see a problem with keeping all four options, as updating old missions becomes a lot more difficult when removing one option. 

**terrain dependent options:**
Assuming we replace our current options with these, when naively updating a mission it could lead to a completely different and unintended AI behaviour (or even scripting errros due to the different number of options). Additionally it becomes impossible to tell which option makes the AI "better" if an admin should choose to make it harder/easier.
I think it's better to either add them additionally to the other 3-4 options we currently have or just advise (using the wiki) to use "Low" skill for jungle missions.


>I'd suggest the following

Just dumping that matrix without any explanation/reasonaning and/or comparison to the old values makes it hard for anyone to understand why we should change anything.
So here's a graphical representation of the suggested changes:
![image](https://user-images.githubusercontent.com/20604336/41819313-a4143128-77be-11e8-8612-dd1ccb368428.png)
Now that we can see the difference the major (proposed) changes seem to be:
* lower the aimingSpeed for lower skill settings.
* lower the spotDistance for higher skill settings.

**Comment by SamLex** [comment] 2018-07-23 22:31
Before this goes further, this needs to be split into two issues. There is the original _refactor_ that should not changes **any** of the final skill values. Then there is the bigger discussion of if the skill values need changed. That is a separate issue.

**Comment by SamLex** [comment] 2019-06-16 08:53
Maybe worth looking at Wolfenswan's [proposed updated values](https://github.com/ferstaberinde/F3/pull/778) on the old repo

**Comment by NikkoJT** [comment] 2021-05-12 14:28
Is this still relevant after the 3.5.5 values change?

**Comment by costno** [comment] 2022-12-08 02:36
Closing this because I think it is no longer relevant.

**Closed by costno** 2022-12-08 02:36 UTC
Labels: T:Component improvement, S0:Needs Additional Info
